### PR TITLE
Allow to specify pulse_liters

### PR DESCRIPTION
**Pull request by krasnoukhov**
Hi @fonske, thanks for shipping me the gear! Proposing this change to make pulse_liters customizable since my clack is set up to give a pulse every 1 liter. Does this make sense?

### CODE REVIEW

**Comment by kalpik** [comment]
Hi! Thanks for this. Have you tested it though? Last time I tried, substitutions weren't available from within lambda, and I'd have to use a global.

**Comment by krasnoukhov** [comment]
I did test it, it's working for me. Substitution required a string so I had to do `int` in the lambda

**Comment by kalpik** [comment]
> I did test it, it's working for me. Substitution required a string so I had to do `int` in the lambda

Perfect! I didn't experiment with strings indeed. Thanks again :)

**Comment by fonske** [comment]
I have changed the integer to float, to be able to calculate with 2.2 instead of 2

**Comment by krasnoukhov** [comment]
Oh that's right @fonske, sorry for that

**Pull request merged**
